{
 "title": "Infinispan-custom",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(vendor_cache_manager_default_number_of_cache_configurations,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vendor_cache_manager_default_number_of_cache_configurations{namespace=~\"$namespace\"}, service)"
    }
   },
   {
    "name": "caches",
    "query": {
     "query": "query_result({job=~\"$cluster\", namespace=~\"$namespace\", __name__=~\"vendor_cache_manager_default_cache_.*_cluster_cache_stats_activations\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Catalog Data Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Off-heap memory Catalog Caches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFProductOfferingCache_statistics_off_heap_memory_used)",
     "legendFormat": "TMFProductOfferingCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFCustomProductOfferingCache_statistics_off_heap_memory_used)",
     "legendFormat": "TMFCustomProductOfferingCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFDofCategoryEshopCache_statistics_off_heap_memory_used)",
     "legendFormat": "TMFDofCategoryEshopCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFDofCategoryCache_statistics_off_heap_memory_used)",
     "legendFormat": "TMFDofCategoryCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_PromotionCache_statistics_off_heap_memory_used)",
     "legendFormat": "PromotionCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_PromotionStaticCache_statistics_off_heap_memory_used)",
     "legendFormat": "PromotionStaticCache"
    }
   ]
  },
  {
   "title": "Catalog caches Off-heap Mem",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFProductOfferingCache_statistics_off_heap_memory_used)",
     "legendFormat": "TMFProductOfferingCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFCustomProductOfferingCache_statistics_off_heap_memory_used)",
     "legendFormat": "TMFCustomProductOfferingCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFDofCategoryEshopCache_statistics_off_heap_memory_used)",
     "legendFormat": "TMFDofCategoryEshopCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFDofCategoryCache_statistics_off_heap_memory_used)",
     "legendFormat": "TMFDofCategoryCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_PromotionCache_statistics_off_heap_memory_used)",
     "legendFormat": "PromotionCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_PromotionStaticCache_statistics_off_heap_memory_used)",
     "legendFormat": "PromotionStaticCache"
    }
   ]
  },
  {
   "title": "Catalog Cache stores/put statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFProductOfferingCache_statistics_stores)",
     "legendFormat": "TMFCustomProductOfferingCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFCustomProductOfferingCache_statistics_stores)\r",
     "legendFormat": "TMFCustomProductOfferingCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFDofCategoryEshopCache_statistics_stores)",
     "legendFormat": "TMFDofCategoryEshopCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_TMFDofCategoryCache_statistics_stores)",
     "legendFormat": "TMFDofCategoryCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_PromotionCache_statistics_stores)",
     "legendFormat": "PromotionCache"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_PromotionStaticCache_statistics_stores)",
     "legendFormat": "PromotionStaticCache"
    }
   ]
  },
  { "title": "Hits/Misses/Puts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Container-level Hits/Misses/Puts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_cache_manager_default_cache_container_stats_hits)",
     "legendFormat": "container_stats_hits"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_container_stats_misses)",
     "legendFormat": "container_stats_misses"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_container_stats_stores)",
     "legendFormat": "container_stats_stores"
    }
   ]
  },
  {
   "title": "Ratio Container misses/hits/puts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vendor_cache_manager_default_cache_container_stats_hits)",
     "legendFormat": "cache_container_stats_hits"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_container_stats_misses)",
     "legendFormat": "container_stats_misses"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_container_stats_stores)",
     "legendFormat": "container_stats_stores"
    }
   ]
  },
  {
   "title": "Cache Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Status",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-cache\"}"
      }
     ]
    },
    {
     "title": "Cache Health Status",
     "type": "gauge",
     "gridPos": { "h": 30, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "probe_http_status_code==204" }
     ]
    }
   ]
  },
  { "title": "Off-Heap Memory per Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Off-heap memory used per Cache",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace({__name__=~\".*_statistics_off_heap_memory_used\"},\"name_label\",\"$1\",\"__name__\",\"(.+)\")) by (__name__)"
    }
   ]
  },
  {
   "title": "Container Off-heap memory by pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vendor_cache_manager_default_cache_container_stats_off_heap_memory_used) by (pod)"
    }
   ]
  },
  {
   "title": "Container Off-heap memory total",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vendor_cache_manager_default_cache_container_stats_off_heap_memory_used)"
    }
   ]
  },
  {
   "title": "Current off-heap memory size per cache",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace({__name__=~\".*_statistics_off_heap_memory_used\"},\"name_label\",\"$1\",\"__name__\",\"(.+)\")) by (__name__)"
    }
   ]
  }
 ]
}