
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: prober-cache
objects:
  - apiVersion: monitoring.coreos.com/v1
    kind: Probe
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${NAME}
    spec:
      interval: ${INTERVAL}
      jobName: ${JOB_NAME}
      module: ${MODULE}
      prober:
        path: /probe
        scheme: http
        url: >-
          ${URL}:9115
      scrapeTimeout: 15s
      targets:
        staticConfig:
          static:
          - 'https://${HOST}/rest/v2/caches/cache1'
          - 'https://${HOST}/rest/v2/caches/cache2'
        tlsConfig:
        insecureSkipVerify: true

parameters:
- name: INTERVAL
- name: HOST
- name: JOB_NAME
- name: URL
- name: APP_NAME
- name: NAME
- name: RHDG_NAMESPACE
- name: MODULE
