
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: prober-cache
objects:
  - apiVersion: monitoring.coreos.com/v1
    kind: Probe
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${NAME}
    spec:
      interval: ${INTERVAL}
      jobName: ${JOB_NAME}
      module: ${MODULE}
      prober:
        path: /probe
        scheme: http
        url: >-
          ${URL}:9115
      scrapeTimeout: 15s
      targets:
        staticConfig:
          static:
          - 'https://${HOST}/rest/v2/caches/groupIdWithDefaultIndicatorCache'
          - 'https://${HOST}/rest/v2/caches/PartyRoleManagementCache'
          - 'https://${HOST}/rest/v2/caches/PartyManagementCache'
          - 'https://${HOST}/rest/v2/caches/gbbBrsMspCache'
          - 'https://${HOST}/rest/v2/caches/ProductRecommendationCache'
          - 'https://${HOST}/rest/v2/caches/OBADetailsCache'
          - 'https://${HOST}/rest/v2/caches/RefundCache'
          - 'https://${HOST}/rest/v2/caches/OrderMatrixCache'
          - 'https://${HOST}/rest/v2/caches/PromotionCache'
          - 'https://${HOST}/rest/v2/caches/PaymentMethodStatusCache'
          - 'https://${HOST}/rest/v2/caches/appointmentCache'
          - 'https://${HOST}/rest/v2/caches/groupShoppingCartCache'
          - 'https://${HOST}/rest/v2/caches/RetailDataGridStatusCache'
          - 'https://${HOST}/rest/v2/caches/QuoteRetrieveDetailCache'
          - 'https://${HOST}/rest/v2/caches/BundleDataGridStatusCache'
          - 'https://${HOST}/rest/v2/caches/rehitCountCache'
          - 'https://${HOST}/rest/v2/caches/DiscoveryCache'
          - 'https://${HOST}/rest/v2/caches/legacyMappingAttributeNameCache'
          - 'https://${HOST}/rest/v2/caches/currentShoppingCache'
          - 'https://${HOST}/rest/v2/caches/ConditionalFlexCache'
          - 'https://${HOST}/rest/v2/caches/PreCacheReloadCache'
          - 'https://${HOST}/rest/v2/caches/dofMessageCache'
          - 'https://${HOST}/rest/v2/caches/otpTokenCache'
          - 'https://${HOST}/rest/v2/caches/ProductInitOrderCache'
          - 'https://${HOST}/rest/v2/caches/SearchTimeSlotResponseCache'
          - 'https://${HOST}/rest/v2/caches/receiverMap'
          - 'https://${HOST}/rest/v2/caches/GeoValidationResultCacheQuarkus'
          - 'https://${HOST}/rest/v2/caches/isPCSCompleted'
          - 'https://${HOST}/rest/v2/caches/MdnSubMarketCache'
          - 'https://${HOST}/rest/v2/caches/AppointmentCache'
          - 'https://${HOST}/rest/v2/caches/ProfileOrderItemsCache'
          - 'https://${HOST}/rest/v2/caches/TMFDofCategoryEshopCache'
          - 'https://${HOST}/rest/v2/caches/___protobuf_metadata'
          - 'https://${HOST}/rest/v2/caches/ServiceQualificationMatrixCache'
          - 'https://${HOST}/rest/v2/caches/GBBProductOfferingQualificationCache'
          - 'https://${HOST}/rest/v2/caches/AnchorBillingAccountsCache'
          - 'https://${HOST}/rest/v2/caches/normalizedMappingNormalizedAttributeCache'
          - 'https://${HOST}/rest/v2/caches/PecOutputCache'
          - 'https://${HOST}/rest/v2/caches/mspConfigurationRequiredCache'
          - 'https://${HOST}/rest/v2/caches/recoIdSubscriberPartyRoleCache'
          - 'https://${HOST}/rest/v2/caches/availableBRSMspCache'
          - 'https://${HOST}/rest/v2/caches/BogoCache'
          - 'https://${HOST}/rest/v2/caches/DataGridStatusCache'
          - 'https://${HOST}/rest/v2/caches/bundleCompletionCache'
          - 'https://${HOST}/rest/v2/caches/TMFCatalogStatusCache'
          - 'https://${HOST}/rest/v2/caches/legacySourceCache'
          - 'https://${HOST}/rest/v2/caches/serviceInventorycache'
          - 'https://${HOST}/rest/v2/caches/PricePlanContractICache'
          - 'https://${HOST}/rest/v2/caches/BillingAccountCache'
          - 'https://${HOST}/rest/v2/caches/historyShoppingCache'
          - 'https://${HOST}/rest/v2/caches/FeaturesCache'
          - 'https://${HOST}/rest/v2/caches/MspConfigurationRequiredCache'
          - 'https://${HOST}/rest/v2/caches/SmartCardReceiversCache'
          - 'https://${HOST}/rest/v2/caches/DeviceHardwarePromoCache'
          - 'https://${HOST}/rest/v2/caches/ServiceQualificationStatusCache'
          - 'https://${HOST}/rest/v2/caches/updateOrderRequiredCache'
          - 'https://${HOST}/rest/v2/caches/EligibleSubGroupCache'
          - 'https://${HOST}/rest/v2/caches/AvailableProductsCache'
          - 'https://${HOST}/rest/v2/caches/individualCache'
          - 'https://${HOST}/rest/v2/caches/TMFCategoryCache'
          - 'https://${HOST}/rest/v2/caches/ShoppingCartCache'
          - 'https://${HOST}/rest/v2/caches/AccountManagementBillingCache'
          - 'https://${HOST}/rest/v2/caches/SmartHomeWebResourceActionCache'
          - 'https://${HOST}/rest/v2/caches/TMFLobCategoryOfferingCache'
          - 'https://${HOST}/rest/v2/caches/XlobActionCache'
          - 'https://${HOST}/rest/v2/caches/PricePlanCache'
          - 'https://${HOST}/rest/v2/caches/AMSS_MessageCache'
          - 'https://${HOST}/rest/v2/caches/BSHProductOrderCache'
          - 'https://${HOST}/rest/v2/caches/AccessoryCache'
          - 'https://${HOST}/rest/v2/caches/GBBOrderItemsCache'
          - 'https://${HOST}/rest/v2/caches/TMFProductSpecificationCache'
          - 'https://${HOST}/rest/v2/caches/RecommendedProfferSOCCache'
          - 'https://${HOST}/rest/v2/caches/brsMSPCompletionCache'
          - 'https://${HOST}/rest/v2/caches/autoConfigCacheBFO'
          - 'https://${HOST}/rest/v2/caches/QuoteOdmRefreshResponseCache'
          - 'https://${HOST}/rest/v2/caches/commonRequestInfoCache'
          - 'https://${HOST}/rest/v2/caches/normalizedViewSourceCache'
          - 'https://${HOST}/rest/v2/caches/PartyAccountSubscriberIDCache'
          - 'https://${HOST}/rest/v2/caches/ProductOfferingListCache'
          - 'https://${HOST}/rest/v2/caches/dofPromoCodeOnOrderCache'
          - 'https://${HOST}/rest/v2/caches/BSHProductOrderHistoryCache'
          - 'https://${HOST}/rest/v2/caches/progEntryCache'
          - 'https://${HOST}/rest/v2/caches/mobilitySessionIdByRecoIdCache'
          - 'https://${HOST}/rest/v2/caches/productOffering679RecoCache'
          - 'https://${HOST}/rest/v2/caches/UiOrderCache'
          - 'https://${HOST}/rest/v2/caches/dofCategoryVisitedCache'
          - 'https://${HOST}/rest/v2/caches/SocInfoCache'
          - 'https://${HOST}/rest/v2/caches/BSHPaymentManagementCache'
          - 'https://${HOST}/rest/v2/caches/ProductDetailsStatusCache'
          - 'https://${HOST}/rest/v2/caches/ProductRecommendationMatrixCache'
          - 'https://${HOST}/rest/v2/caches/relatedPatyRecoCache'
          - 'https://${HOST}/rest/v2/caches/recommendedProductsCache'
          - 'https://${HOST}/rest/v2/caches/GroupSharingSocsCache'
          - 'https://${HOST}/rest/v2/caches/SmartHomeProductConfigCache'
          - 'https://${HOST}/rest/v2/caches/RegularSocCache'
          - 'https://${HOST}/rest/v2/caches/SubGroupsBunldeConfig'
          - 'https://${HOST}/rest/v2/caches/PecFlowStartTimeCache'
          - 'https://${HOST}/rest/v2/caches/PartyManagementOrganizationCache'
          - 'https://${HOST}/rest/v2/caches/OneTimeChargeCache'
          - 'https://${HOST}/rest/v2/caches/OptionalSocsMapCache'
          - 'https://${HOST}/rest/v2/caches/SchedulerStatusCache'
          - 'https://${HOST}/rest/v2/caches/TMFProductOfferingCache'
          - 'https://${HOST}/rest/v2/caches/SmartCardDataCache'
          - 'https://${HOST}/rest/v2/caches/historyBceOrderCache'
          - 'https://${HOST}/rest/v2/caches/GetPricePlansCache'
          - 'https://${HOST}/rest/v2/caches/manualOfferCache'
          - 'https://${HOST}/rest/v2/caches/PromoCodeProductOfferingCache'
          - 'https://${HOST}/rest/v2/caches/subscriberPartyRole'
          - 'https://${HOST}/rest/v2/caches/QueryProductRecommendationCacheStatus'
          - 'https://${HOST}/rest/v2/caches/keyListCache'
          - 'https://${HOST}/rest/v2/caches/RETRIEVE_BROWSINGCAT_FILTER_FACETS_EN'
          - 'https://${HOST}/rest/v2/caches/RvaOrderMatrixCache'
          - 'https://${HOST}/rest/v2/caches/dofPromoCodeCache'
          - 'https://${HOST}/rest/v2/caches/DataProductCache'
          - 'https://${HOST}/rest/v2/caches/dofPromocodeMsgCodeCache'
          - 'https://${HOST}/rest/v2/caches/TMFCustomProductOfferingCache'
          - 'https://${HOST}/rest/v2/caches/maxReceiverCache'
          - 'https://${HOST}/rest/v2/caches/PreCacheStatusReportDetailsCache'
          - 'https://${HOST}/rest/v2/caches/TMFDofCategoryCache'
          - 'https://${HOST}/rest/v2/caches/UiProductOrderCache'
          - 'https://${HOST}/rest/v2/caches/DeviceNameAndIdCache'
          - 'https://${HOST}/rest/v2/caches/ProcessFlowCache'
          - 'https://${HOST}/rest/v2/caches/shoppingCart663RecoCache'
          - 'https://${HOST}/rest/v2/caches/groupTmf679Cache'
          - 'https://${HOST}/rest/v2/caches/QueryServiceQualificationCache'
          - 'https://${HOST}/rest/v2/caches/RvaProcessFlowStatusCache'
          - 'https://${HOST}/rest/v2/caches/cache-xsite'
          - 'https://${HOST}/rest/v2/caches/CGValidationResultCacheQuarkus'
          - 'https://${HOST}/rest/v2/caches/SmartHomeCatalogConfigCache'
          - 'https://${HOST}/rest/v2/caches/BogoDevicecConfigurationCache'
          - 'https://${HOST}/rest/v2/caches/ServiceQualCache'
          - 'https://${HOST}/rest/v2/caches/RETRIEVE_BROWSINGCAT_FILTER_FACETS_FR'
          - 'https://${HOST}/rest/v2/caches/TMFCatalogCache'
          - 'https://${HOST}/rest/v2/caches/SearchCache'
          - 'https://${HOST}/rest/v2/caches/dofPromoCodeImpactedCache'
          - 'https://${HOST}/rest/v2/caches/servicelocationcache'
          - 'https://${HOST}/rest/v2/caches/resumeOrderCompletionCache'
          - 'https://${HOST}/rest/v2/caches/dofMDNDetailsCache'
          - 'https://${HOST}/rest/v2/caches/GroupSharingSocsDetailCache'
          - 'https://${HOST}/rest/v2/caches/schedulerRefreshCallInfo'
          - 'https://${HOST}/rest/v2/caches/SmartHomeProductConfigUndoChangeCache'
          - 'https://${HOST}/rest/v2/caches/salesRepCache'
          - 'https://${HOST}/rest/v2/caches/GroupDetailsCache'
          - 'https://${HOST}/rest/v2/caches/impactedOfferCache'
          - 'https://${HOST}/rest/v2/caches/DataGridDataStatusCache'
          - 'https://${HOST}/rest/v2/caches/ProductOfferingCache'
          - 'https://${HOST}/rest/v2/caches/cityAndProvinceMap'
          - 'https://${HOST}/rest/v2/caches/GetRegularSocCache'
          - 'https://${HOST}/rest/v2/caches/socGroupsToBeEligibe'
          - 'https://${HOST}/rest/v2/caches/AccountManagementPartyCache'
          - 'https://${HOST}/rest/v2/caches/ShoppingCartStatusCache'
          - 'https://${HOST}/rest/v2/caches/MDNReleaseStatusCache'
          - 'https://${HOST}/rest/v2/caches/AppointmentApiOrderContextCache'
          - 'https://${HOST}/rest/v2/caches/ProcessFlowStatusCache'
          - 'https://${HOST}/rest/v2/caches/ProductOfferingStatusCache'
          - 'https://${HOST}/rest/v2/caches/ProductOrderCache'
          - 'https://${HOST}/rest/v2/caches/TMF637ProductInventoryEntityCache'
          - 'https://${HOST}/rest/v2/caches/SearchOfferingListCache'
          - 'https://${HOST}/rest/v2/caches/PendingOrderCache'
          - 'https://${HOST}/rest/v2/caches/SmartHomeCustomerDetailsCache'
          - 'https://${HOST}/rest/v2/caches/EntitledProductsCache'
          - 'https://${HOST}/rest/v2/caches/mobilityHardStopMsgsCache'
          - 'https://${HOST}/rest/v2/caches/CityListCache'
          - 'https://${HOST}/rest/v2/caches/HardwarePromoInstallmentSubmissionCache'
          - 'https://${HOST}/rest/v2/caches/RetailNavigationCache'
          - 'https://${HOST}/rest/v2/caches/eligibleSpecialPromotions'
          - 'https://${HOST}/rest/v2/caches/WebBillingAccountCache'
          - 'https://${HOST}/rest/v2/caches/dofInternalPromoCodeCache'
          - 'https://${HOST}/rest/v2/caches/SubGroupCache'
          - 'https://${HOST}/rest/v2/caches/PricePlanCacheKeysCache'
          - 'https://${HOST}/rest/v2/caches/ResourceActionCache'
          - 'https://${HOST}/rest/v2/caches/GroupSharingSocsMapCache'
          - 'https://${HOST}/rest/v2/caches/SmartHomeOrderContextCache'
          - 'https://${HOST}/rest/v2/caches/GetHardwarePromoCache'
          - 'https://${HOST}/rest/v2/caches/RvaTaskFlowCache'
          - 'https://${HOST}/rest/v2/caches/BogoDeviceOfferingCache'
          - 'https://${HOST}/rest/v2/caches/OrderIdsCache'
          - 'https://${HOST}/rest/v2/caches/OptionalSocPreCache'
          - 'https://${HOST}/rest/v2/caches/finalScheduleCache'
          - 'https://${HOST}/rest/v2/caches/PaymentMethodCache'
          - 'https://${HOST}/rest/v2/caches/RvaProcessFlowCache'
          - 'https://${HOST}/rest/v2/caches/sample-cache'
          - 'https://${HOST}/rest/v2/caches/PreCachingRefreshDeltaMSG'
          - 'https://${HOST}/rest/v2/caches/RecommendationResponseCache'
          - 'https://${HOST}/rest/v2/caches/promoCodebrsMSPCompletionCache'
          - 'https://${HOST}/rest/v2/caches/IncompatibleSocMultiLineCache'
          - 'https://${HOST}/rest/v2/caches/AvailableProductsHistoryCache'
          - 'https://${HOST}/rest/v2/caches/BSHProductOrderApiCache'
          - 'https://${HOST}/rest/v2/caches/PrePortStatusCache'
          - 'https://${HOST}/rest/v2/caches/PostalCodeCache'
          - 'https://${HOST}/rest/v2/caches/ProfileProductsCache'
          - 'https://${HOST}/rest/v2/caches/MdnExpiredListenerCache'
          - 'https://${HOST}/rest/v2/caches/WirelessUsageSummaryCache'
          - 'https://${HOST}/rest/v2/caches/WinbackIdentifiers'
          - 'https://${HOST}/rest/v2/caches/addRemoveLobCompletionCache'
          - 'https://${HOST}/rest/v2/caches/BffCache'
          - 'https://${HOST}/rest/v2/caches/RetailActionCache'
          - 'https://${HOST}/rest/v2/caches/SmartHomeQuotationDetailsCache'
          - 'https://${HOST}/rest/v2/caches/MultiLineOfferCache'
          - 'https://${HOST}/rest/v2/caches/orderEntryUserCache'
          - 'https://${HOST}/rest/v2/caches/TMFProductOfferingPriceCache'
          - 'https://${HOST}/rest/v2/caches/PromoCodeCharacteristicsCache'
          - 'https://${HOST}/rest/v2/caches/PaymentCache'
          - 'https://${HOST}/rest/v2/caches/normalizedMappingProductOfferingCache'
          - 'https://${HOST}/rest/v2/caches/BuildVersionCache'
          - 'https://${HOST}/rest/v2/caches/productCatalogDetailsCache'
          - 'https://${HOST}/rest/v2/caches/SOCParametersCache'
          - 'https://${HOST}/rest/v2/caches/legacyMappingProductOfferingCache'
          - 'https://${HOST}/rest/v2/caches/recoShoppingCartCache'
          - 'https://${HOST}/rest/v2/caches/ProductDetailsCache'
          - 'https://${HOST}/rest/v2/caches/GetOptionalSocCache'
          - 'https://${HOST}/rest/v2/caches/GetSocInfoeMapCache'
          - 'https://${HOST}/rest/v2/caches/mspNonMSPRecommendationsCache'
          - 'https://${HOST}/rest/v2/caches/HardwarePromoSubmissionCache'
          - 'https://${HOST}/rest/v2/caches/RecommendationCache'
          - 'https://${HOST}/rest/v2/caches/MulitLineOfferIncentiveEligibilityMap'
          - 'https://${HOST}/rest/v2/caches/BSHProductOfferingCache'
          - 'https://${HOST}/rest/v2/caches/QueryProductRecommendationCache'
          - 'https://${HOST}/rest/v2/caches/retrieveOrderCache'
          - 'https://${HOST}/rest/v2/caches/ProductOrderHistoryCache'
          - 'https://${HOST}/rest/v2/caches/PaymentManagementStatusCache'
          - 'https://${HOST}/rest/v2/caches/OrderContextCache'
          - 'https://${HOST}/rest/v2/caches/DofRvaProcessResourceCache'
          - 'https://${HOST}/rest/v2/caches/TMF637ProductInventoryEntityStatusCache'
          - 'https://${HOST}/rest/v2/caches/crateOrderParamsAtInitCache'
          - 'https://${HOST}/rest/v2/caches/CheckServiceQualificationCache'
          - 'https://${HOST}/rest/v2/caches/MobilityProductOrderCache'
          - 'https://${HOST}/rest/v2/caches/DefaultContractOptionsCache'
          - 'https://${HOST}/rest/v2/caches/InventoryCheckCache'
          - 'https://${HOST}/rest/v2/caches/BSHPartyManagementApiCache'
          - 'https://${HOST}/rest/v2/caches/callBackCache'
          - 'https://${HOST}/rest/v2/caches/TaskFlowCache'
          - 'https://${HOST}/rest/v2/caches/___script_cache'
        tlsConfig:
        insecureSkipVerify: true

parameters:
- name: INTERVAL
- name: HOST
- name: JOB_NAME
- name: URL
- name: APP_NAME
- name: NAME
- name: RHDG_NAMESPACE
- name: MODULE
